#! /bin/bash
echo "ADDING THIS FILE TO GIT(1/0)?"
read Ans

if ["$Ans" == "1"];then	
	git init
	git add . 
	git commit -m 'First commit'
	echo -n "Copy the Https of the page and enter it here >"
	read https_key
	git remote add origin $https_key
	git remote -v
	git push origin master
	echo "THIS FOLDER IS NOW ON GIT"
fi

if ["$Ans" == "1"];then
	echo "FOLDER UNTOUCHED"
fi 

if ["$Ans" != "0" || "$Ans" != "1"]; then
	echo "PLEASE ENTER 1 or 0"
